# Generated by Django 2.1.5 on 2019-01-27 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20190127_1926'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='img',
            field=models.ImageField(blank=True, height_field='400', upload_to='blog/photos', verbose_name='Картинка', width_field='300'),
        ),
    ]
