# Generated by Django 2.1.5 on 2019-02-10 11:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20190127_1944'),
    ]

    operations = [
        migrations.CreateModel(
            name='Create_post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('autor', models.CharField(max_length=10, verbose_name='Ник автора')),
                ('email', models.EmailField(max_length=30, verbose_name='Контакт автора')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Дата')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Article', verbose_name='Статья')),
            ],
        ),
    ]
